### ISSUE TITLE
Upgrade to latest OC preview to test System.Text.Json (OSOE-795)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Open-Source-Orchard-Core-Extensions#692]
After https://github.com/OrchardCMS/OrchardCore/pull/14572, OC now uses `System.Text.Json` instead of Json.NET. So, let's upgrade to this preview version and test if anything is broken.

- [x] Open a `task/system-text-json-migration` branch from `dev` and start your issue branch from there. After this issue is done, we won't yet merge this to `dev`, waiting for that for OC v2.0.
- [x] Upgrade OC as usual.
- [x] Change all of our code that uses Json.NET to use STJ instead.
- [x] The https://github.com/OrchardCMS/OrchardCore/pull/13181 PR [changed the registration order of the authentication middleware](https://github.com/OrchardCMS/OrchardCore/pull/13181/files#diff-79fbaf725f0ce29f3982bdf05070824259b3cb3e0f5a523324151423cadef58cL520). This might break [`BlockMediaThemeTemplateDirectAccessMiddleware`](https://github.com/Lombiq/Hosting-Media-Theme/blob/dev/Lombiq.Hosting.MediaTheme.Bridge/Middlewares/BlockMediaThemeTemplateDirectAccessMiddleware.cs). Be sure it's not broken.
- [x] Issues like https://github.com/OrchardCMS/OrchardCore/issues/15628 can now be made apparent, even with SQLite, with the new `EnableThreadSafetyChecks` YesSql config. Please enable those for UI tests, see https://github.com/OrchardCMS/OrchardCore/pull/15961.
- [x] For every general OC issue we find, open an OC issue.
  - https://github.com/OrchardCMS/OrchardCore/issues/15397
  - https://github.com/OrchardCMS/OrchardCore/issues/15451
  - https://github.com/OrchardCMS/OrchardCore/issues/15497
  - https://github.com/OrchardCMS/OrchardCore/issues/15505
  - https://github.com/OrchardCMS/OrchardCore/issues/15533
  - https://github.com/OrchardCMS/OrchardCore/issues/15628
  - https://github.com/OrchardCMS/OrchardCore/issues/15975

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-795)

**Comment by Piedone** [comment]
Something you might be interested in @sarahelsaig?

**Comment by sarahelsaig** [comment]
Yes!

**Comment by Piedone** [comment]
It's yours, then :).

**Comment by sarahelsaig** [comment]
Almost done, except the SQL Server UI tests fail now, of all things. I've pasted the message below. Do you have any hint, @Piedone ? I recall recently you did an issue related to `MultipleActiveResultSets`.

```
2024-03-18 02:20:09.5435|Default|00-d897ab0f006a4b692dcc0d6793ea5912-e6ed5a8c98c88afb-00||OrchardCore.Environment.Shell.ShellFeaturesManager|ERROR|IFeatureEventHandler thrown from OrchardCore.Roles.Services.RoleUpdater by InvalidOperationException System.InvalidOperationException: The connection does not support MultipleActiveResultSets.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 434
   at YesSql.Store.ProduceAsync[T,TState](WorkerQueryKey key, Func`2 work, TState state)
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at OrchardCore.Data.Documents.DocumentStore.GetOrCreateMutableAsync[T](Func`1 factoryAsync)
   at OrchardCore.Documents.DocumentManager`1.GetOrCreateMutableAsync(Func`1 factoryAsync)
   at OrchardCore.Roles.Services.RoleUpdater.UpdateRolesForInstalledFeatureAsync(IFeatureInfo feature)
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger)    at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 434
   at YesSql.Store.ProduceAsync[T,TState](WorkerQueryKey key, Func`2 work, TState state)
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at OrchardCore.Data.Documents.DocumentStore.GetOrCreateMutableAsync[T](Func`1 factoryAsync)
   at OrchardCore.Documents.DocumentManager`1.GetOrCreateMutableAsync(Func`1 factoryAsync)
   at OrchardCore.Roles.Services.RoleUpdater.UpdateRolesForInstalledFeatureAsync(IFeatureInfo feature)
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger)
2024-03-18 02:20:11.0334|Default|00-d897ab0f006a4b692dcc0d6793ea5912-e6ed5a8c98c88afb-00||OrchardCore.Environment.Shell.ShellFeaturesManager|ERROR|IFeatureEventHandler thrown from OrchardCore.Roles.Services.RoleUpdater by InvalidOperationException System.InvalidOperationException: The connection does not support MultipleActiveResultSets.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 434
   at YesSql.Store.ProduceAsync[T,TState](WorkerQueryKey key, Func`2 work, TState state)
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at OrchardCore.Data.Documents.DocumentStore.GetOrCreateMutableAsync[T](Func`1 factoryAsync)
   at OrchardCore.Documents.DocumentManager`1.GetOrCreateMutableAsync(Func`1 factoryAsync)
   at OrchardCore.Roles.Services.RoleUpdater.UpdateRolesForInstalledFeatureAsync(IFeatureInfo feature)
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger)    at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 434
   at YesSql.Store.ProduceAsync[T,TState](WorkerQueryKey key, Func`2 work, TState state)
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at OrchardCore.Data.Documents.DocumentStore.GetOrCreateMutableAsync[T](Func`1 factoryAsync)
   at OrchardCore.Documents.DocumentManager`1.GetOrCreateMutableAsync(Func`1 factoryAsync)
   at OrchardCore.Roles.Services.RoleUpdater.UpdateRolesForInstalledFeatureAsync(IFeatureInfo feature)
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger)
```

**Comment by Piedone** [comment]
Yes, see https://github.com/Lombiq/UI-Testing-Toolbox/issues/343 and https://github.com/OrchardCMS/OrchardCore/issues/15224. This looks like an OC bug in the Roles module (and a new one since 1.8), then, most possibly some unwanted multi-threaded SQL query. Please add details to the OC issue and fix it if you can.

**Comment by Piedone** [comment]
The https://github.com/OrchardCMS/OrchardCore/pull/13181 PR [changed the registration order of the authentication middleware](https://github.com/OrchardCMS/OrchardCore/pull/13181/files#diff-79fbaf725f0ce29f3982bdf05070824259b3cb3e0f5a523324151423cadef58cL520). This might break [`BlockMediaThemeTemplateDirectAccessMiddleware`](https://github.com/Lombiq/Hosting-Media-Theme/blob/dev/Lombiq.Hosting.MediaTheme.Bridge/Middlewares/BlockMediaThemeTemplateDirectAccessMiddleware.cs). Please make sure it's not broken.

**Comment by Piedone** [comment]
Now the blocking bugs are fixed, so tomorrow morning the updated packages should be on Cloudsmith. Please also see the localization thing I added above.

**Comment by sarahelsaig** [comment]
Oh, what a relief! I will update the packages and validate the results during the weekend.

**Comment by Piedone** [comment]
Thanks! FYI @MikeAlhayek.

**Comment by Piedone** [comment]
Issues like https://github.com/OrchardCMS/OrchardCore/issues/15628 can now be made apparent, even with SQLite, with the new `EnableThreadSafetyChecks` YesSql config. Please enable those for UI tests, see https://github.com/OrchardCMS/OrchardCore/pull/15961.

**Comment by Piedone** [comment]
Is this intentionally not closed @dministro?
